BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "login_sessions" (
	"uid"	INTEGER NOT NULL UNIQUE,
	"key"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("uid")
);
CREATE TABLE IF NOT EXISTS "listings" (
	"id"	INTEGER NOT NULL UNIQUE,
	"uid"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"type"	INTEGER,
	"status"	INTEGER NOT NULL DEFAULT 0,
	"price"	INTEGER,
	"want"	TEXT,
	"have"	TEXT,
	"category"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "accounts" (
	"id"	INTEGER NOT NULL UNIQUE,
	"username"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"salt"	TEXT NOT NULL,
	"email"	TEXT NOT NULL UNIQUE,
	"created_time"	INTEGER NOT NULL,
	"last_login"	INTEGER NOT NULL,
	"saved"	TEXT,
	"admin"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "chats" (
	"id"	INTEGER NOT NULL UNIQUE,
	"listingId"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "messages" (
	"id"	INTEGER NOT NULL UNIQUE,
	"chatId"	INTEGER NOT NULL,
	"from"	INTEGER NOT NULL,
	"to"	INTEGER NOT NULL,
	"message"	TEXT NOT NULL,
	"timestamp"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
